apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}-svc
  namespace: {{ .Values.namespace }}
spec:
  ports:
  - name: {{ .Values.name }}-svc
    protocol: TCP
    port: {{ .Values.port }}
    targetPort: 8080
  type: NodePort
  selector:
    name: {{ .Values.name }}
